version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./volumes/mysqldata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal_mysql
      MYSQL_USER: lportal
      MYSQL_PASSWORD: lportal
    restart: always
  portal:
    build: ./mysql/
    volumes:
      - "./tmp/deploy:/opt/liferay-portal/deploy"
      - "./volumes/liferaydata:/opt/liferay-portal/data"
      - "./volumes/logs:/opt/liferay-portal/tomcat-7.0.62/logs"
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8181:8080"
    restart: always
