version: '2'
services:
  portal:
    build: ./hsql/
    volumes:
      - "./tmp/deploy:/opt/liferay-portal/deploy"
      - "./volumes/liferaydata:/opt/liferay-portal/data"
      - "./volumes/logs:/opt/liferay-portal/tomcat-7.0.62/logs"
    ports:
      - "8080:8080"
    restart: always
